services:
  # ==========================================
  # AMBIENTE DE DESENVOLVIMENTO (Localhost)
  # ==========================================
#  iata_dev:
#    build: .
#    container_name: iata
#    ports:
#      - "8003:8003"
#    volumes:
#      - .:/code  # Monta sua pasta local dentro do container (Hot Reload)
#    environment:
#      - DEBUG=True
#    # Sobrescreve o comando para ativar o --reload
#    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
#    restart: unless-stopped
#    networks:
#      - nativa-net

  # ==========================================
  # AMBIENTE DE PRODUÇÃO (VPS)
  # Descomente abaixo e comente o serviço acima quando for subir na VPS
  # ==========================================
  iata_prod:
    build: .
    container_name: iata
    ports:
      - "8003:8003"
    # Em produção não usamos volumes de código, usamos o COPY do Dockerfile
    restart: always
    networks:
      - nativa-net

networks:
  nativa-net:
    external: true