-- ============================================
-- ChatDatajud — DDL (Schema)
-- ============================================

-- Tabela CN (Casos Novos) — 27 colunas
CREATE TABLE cn (
    id                    SERIAL PRIMARY KEY,
    tribunal              VARCHAR(20) NOT NULL,
    grau                  VARCHAR(5),
    nome_orgao            VARCHAR(200),
    uf                    CHAR(2),
    municipio             VARCHAR(100),
    ano                   SMALLINT NOT NULL,
    mes                   SMALLINT NOT NULL,
    processo              VARCHAR(30),
    codigo_ultima_classe  INTEGER,
    nome_ultima_classe    VARCHAR(200),
    codigos_classes       TEXT,
    codigos_assuntos      TEXT,
    data_referencia       DATE,
    formato               VARCHAR(30),
    procedimento          VARCHAR(80),
    recurso               VARCHAR(10),
    codigo_orgao          INTEGER,
    id_municipio          INTEGER,
    polo_ativo            TEXT,
    polo_ativo_cnpj       TEXT,
    polo_ativo_natureza   TEXT,
    polo_ativo_cnae       TEXT,
    polo_passivo          TEXT,
    polo_passivo_cnpj     TEXT,
    polo_passivo_natureza TEXT,
    polo_passivo_cnae     TEXT,
    poder_publico         VARCHAR(60)
);

-- Tabela SENT (Sentenças) — 29 colunas
CREATE TABLE sent (
    id                              SERIAL PRIMARY KEY,
    tribunal                        VARCHAR(20) NOT NULL,
    grau                            VARCHAR(5),
    nome_orgao                      VARCHAR(200),
    uf                              CHAR(2),
    municipio                       VARCHAR(100),
    ano                             SMALLINT NOT NULL,
    mes                             SMALLINT NOT NULL,
    processo                        VARCHAR(30),
    codigos_classes                 TEXT,
    codigo_ultima_classe            INTEGER,
    nome_ultima_classe              VARCHAR(200),
    codigos_assuntos                TEXT,
    data_referencia                 DATE,
    data_julgamento_sit_mov         TEXT,
    data_decisao_sit_mov            TEXT,
    formato                         VARCHAR(30),
    procedimento                    VARCHAR(80),
    recurso                         VARCHAR(10),
    codigo_orgao                    INTEGER,
    id_municipio                    INTEGER,
    polo_ativo                      TEXT,
    polo_ativo_cnpj                 TEXT,
    polo_ativo_natureza             TEXT,
    polo_ativo_cnae                 TEXT,
    polo_passivo                    TEXT,
    polo_passivo_cnpj               TEXT,
    polo_passivo_natureza           TEXT,
    polo_passivo_cnae               TEXT,
    poder_publico                   VARCHAR(60)
);

-- Tabela TBAIX (Casos Baixados) — 29 colunas
CREATE TABLE tbaix (
    id                    SERIAL PRIMARY KEY,
    tribunal              VARCHAR(20) NOT NULL,
    grau                  VARCHAR(5),
    nome_orgao            VARCHAR(200),
    uf                    CHAR(2),
    municipio             VARCHAR(100),
    ano                   SMALLINT NOT NULL,
    mes                   SMALLINT NOT NULL,
    processo              VARCHAR(30),
    codigo_ultima_classe  INTEGER,
    nome_ultima_classe    VARCHAR(200),
    codigos_classes       TEXT,
    codigos_assuntos      TEXT,
    data_inicio           DATE,
    data_referencia       DATE,
    formato               VARCHAR(30),
    procedimento          VARCHAR(80),
    recurso_originario    VARCHAR(30),
    recurso               VARCHAR(10),
    codigo_orgao          INTEGER,
    id_municipio          INTEGER,
    polo_ativo            TEXT,
    polo_ativo_cnpj       TEXT,
    polo_ativo_natureza   TEXT,
    polo_ativo_cnae       TEXT,
    polo_passivo          TEXT,
    polo_passivo_cnpj     TEXT,
    polo_passivo_natureza TEXT,
    polo_passivo_cnae     TEXT,
    poder_publico         VARCHAR(60)
);

-- Tabela CPL (Casos Pendentes / Congestionamento) — 39 colunas
CREATE TABLE cpl (
    id                        SERIAL PRIMARY KEY,
    tribunal                  VARCHAR(20) NOT NULL,
    grau                      VARCHAR(5),
    uf                        CHAR(2),
    municipio                 VARCHAR(100),
    nome_orgao                VARCHAR(200),
    ano                       SMALLINT NOT NULL,
    mes                       SMALLINT NOT NULL,
    processo                  VARCHAR(30),
    codigo_ultima_classe      INTEGER,
    nome_ultima_classe        VARCHAR(200),
    codigos_classes           TEXT,
    codigos_assuntos          TEXT,
    data_ajuizamento          DATE,
    data_inicio               DATE,
    data_primeiro_julgamento  DATE,
    data_julgamento_sit_mov   TEXT,
    data_decisao_sit_mov      TEXT,
    data_ultima_movimentacao  DATE,
    inicio_ultima_conclusao   TEXT,
    tipo_conclusao            VARCHAR(60),
    datas_inicio_fim          TEXT,
    dias_antiguidade          INTEGER,
    formato                   VARCHAR(30),
    procedimento              VARCHAR(80),
    recurso_originario        VARCHAR(30),
    recurso                   VARCHAR(10),
    codigo_orgao              INTEGER,
    id_municipio              INTEGER,
    polo_ativo                TEXT,
    polo_ativo_cnpj           TEXT,
    polo_ativo_natureza       TEXT,
    polo_ativo_cnae           TEXT,
    polo_passivo              TEXT,
    polo_passivo_cnpj         TEXT,
    polo_passivo_natureza     TEXT,
    polo_passivo_cnae         TEXT,
    poder_publico             VARCHAR(60),
    liquido                   CHAR(1),
    mais_15_anos              CHAR(1)
);

-- Tabela DATAMART (Analítico Completo) — ~170 colunas (todas TEXT para flexibilidade)
CREATE TABLE datamart (
    id SERIAL PRIMARY KEY,
    -- Identificação
    sigla_tribunal TEXT,
    id_tribunal TEXT,
    sigla_grau TEXT,
    procedimento TEXT,
    sistema TEXT,
    id_processo TEXT,
    numero_sigilo TEXT,
    id_ultimo_oj TEXT,
    valor_causa TEXT,
    id_classe TEXT,
    id_assunto TEXT,
    ids_orgao_julgador TEXT,
    id_orgao_julgador TEXT,
    recurso TEXT,
    id_classes_cn TEXT,
    id_ultima_classe TEXT,
    -- Datas do Ciclo de Vida
    data_ultima_movimentacao TEXT,
    data_ajuizamento TEXT,
    dt_recebimento TEXT,
    dt_pendente TEXT,
    dt_baixa TEXT,
    dt_primeira_remessa TEXT,
    dt_arquivamento TEXT,
    dt_pendente_liquido TEXT,
    data_total_primeira_baixa TEXT,
    data_total_primeiro_julgamento TEXT,
    data_total_inicio_ultimo_pendente_liquido TEXT,
    data_total_ultimo_pendente_liquido TEXT,
    data_total_ultimo_pendente TEXT,
    data_total_ultima_suspensao TEXT,
    -- Datas de Julgamento
    data_total_primeiro_julgamento_sem_pronuncia TEXT,
    data_total_primeiro_procedimento_resolvido TEXT,
    dt_admissao_recurso_especial TEXT,
    dt_nao_admissao_recurso_especial TEXT,
    dt_admissao_recurso_extraordinario TEXT,
    dt_nao_admissao_recurso_extraordinario TEXT,
    dt_admissao_recurso_revista TEXT,
    dt_nao_admissao_recurso_revista TEXT,
    dt_negado_seguimento TEXT,
    dt_concluso TEXT,
    dt_julgamento TEXT,
    dt_julgamento_movimento TEXT,
    dt_julgamento_merito TEXT,
    dt_dessobrestamento TEXT,
    -- Datas de Decisão
    dt_julgamento_sem_merito TEXT,
    dt_julgamento_homologatorio TEXT,
    dt_primeiro_julgamento TEXT,
    dt_primeiro_julgamento_merito TEXT,
    dt_primeiro_julgamento_homologatorio TEXT,
    dt_primeiro_julgamento_nao_cautelar TEXT,
    dt_primeiro_julgamento_homologatorio_nao_cautelar TEXT,
    dt_despacho TEXT,
    dt_decisao TEXT,
    dt_decisao_movimento TEXT,
    dt_audiencia TEXT,
    dt_audiencia_conc TEXT,
    dt_liminar_deferida TEXT,
    dt_liminar_indeferida TEXT,
    -- Redistribuição e Recursos
    dt_redistribuido_entrada TEXT,
    dt_redistribuido_saida TEXT,
    dt_reativacao TEXT,
    dt_reativacao_fim TEXT,
    dt_rec_inc_novo TEXT,
    dt_rec_inc_pendente TEXT,
    dt_rec_inc_julgado TEXT,
    dt_julg_decisao_ed TEXT,
    -- Medidas Protetivas
    dt_primeira_medida_protetiva TEXT,
    dt_medida_protetiva TEXT,
    dt_medida_protetiva_concedida TEXT,
    dt_medida_protetiva_nao_concedida TEXT,
    dt_medida_protetiva_homologada TEXT,
    dt_medida_protetiva_revogada_autoridade_policial TEXT,
    dt_medida_protetiva_revogada TEXT,
    dt_medida_protetiva_prorrogada TEXT,
    -- Resultados Julgamento
    dt_sessao_juri_realizada TEXT,
    dt_procedencia TEXT,
    dt_improcedencia TEXT,
    dt_procedencia_em_parte TEXT,
    dt_rec_provido TEXT,
    dt_rec_desprovido TEXT,
    dt_rec_nao_conhecido TEXT,
    dt_rec_negado TEXT,
    dt_rec_prejudicado TEXT,
    dt_confirmacao_sent TEXT,
    dt_desconstituicao_sent TEXT,
    dt_anulacao_sent TEXT,
    dt_pronuncia TEXT,
    dt_impronuncia TEXT,
    dt_absolvicao_sumaria TEXT,
    dt_desclassificacao TEXT,
    -- Extinção
    dt_extincao_morte TEXT,
    dt_extincao_prescricao TEXT,
    dt_extincao_decadencia TEXT,
    dt_extincao_cumprimento TEXT,
    dt_extincao_outros TEXT,
    -- Audiências
    dt_cooperacao_judiciaria TEXT,
    dt_audiencia_concentrada_realizada TEXT,
    dt_audiencia_instrucao_realizada TEXT,
    dt_audiencia_art16_maria_penha_realizada TEXT,
    dt_audiencia_preliminar_realizada TEXT,
    dt_audiencia_acolhimento_realizada TEXT,
    dt_audiencia_justificacao_realizada TEXT,
    -- Suspensões
    dt_ato_infracional_iniciado TEXT,
    dt_suspensao_rg TEXT,
    dt_suspensao_rr TEXT,
    dt_suspensao_rrr TEXT,
    dt_suspensao_irdr TEXT,
    dt_suspensao_iac TEXT,
    dt_suspensao_sirdr TEXT,
    dt_suspensao_controle_constitucionalidade TEXT,
    dt_suspensao_acao_coletiva TEXT,
    -- ANPP
    dt_suspensao_preju_re TEXT,
    dt_homologacao_anpp TEXT,
    dt_revogacao_anpp TEXT,
    dt_cumprimento_anpp TEXT,
    -- Metadados Processuais
    id_procedimento TEXT,
    proc_cn TEXT,
    originario TEXT,
    formato TEXT,
    id_ultima_classe_cn TEXT,
    nome TEXT,
    ramo_justica TEXT,
    data_total_inicio TEXT,
    data_total_pendente TEXT,
    data_total_pendente_liquido_meta TEXT,
    -- Status e Conclusão
    sem_tramitacao TEXT,
    sem_conclusao TEXT,
    ultima_conclusao_generica TEXT,
    ultima_conclusao_despacho TEXT,
    ultima_conclusao_decisao TEXT,
    ultima_conclusao_julgamento TEXT,
    ultima_conclusao_admissibilidade_recursal TEXT,
    tipo_conclusao TEXT,
    antigos TEXT,
    -- Tipos de Status
    tp_julg_st TEXT,
    tp_julg_merito_st TEXT,
    tp_medprot_st TEXT,
    tp_baix_st TEXT,
    tp_arq_st TEXT,
    -- Órgão Julgador
    orgao_julgador TEXT,
    uf_oj TEXT,
    id_municipio TEXT,
    municipio_oj TEXT,
    tipo_unidade TEXT,
    classificacao_unidade TEXT,
    flg_balcao_virtual TEXT,
    flg_juizo_digital TEXT,
    dat_adesao_juizo_digital TEXT,
    dat_termino_juizo_digital TEXT,
    -- Competência
    dat_instalacao TEXT,
    seq_lista_competencia_juizo TEXT,
    competencia TEXT,
    competencia_exclusiva TEXT,
    competencia_tipo TEXT,
    competencia_grupo TEXT,
    -- Classificação
    situacao TEXT,
    classe TEXT,
    -- Flags Temáticas
    flag_violencia_domestica TEXT,
    flag_feminicidio TEXT,
    flag_violencia_domestica_premio TEXT,
    flag_feminicidio_premio TEXT,
    flag_medida_protetiva_premio TEXT,
    flag_seeu TEXT,
    flag_ambiental TEXT,
    flag_ambiental_premio TEXT,
    flag_trabalho_escravo TEXT,
    flag_indigenas TEXT,
    flag_quilombolas TEXT,
    flag_juri TEXT,
    flag_saude_publica TEXT,
    flag_saude_complementar TEXT,
    flag_saude TEXT,
    flag_assistencial TEXT,
    flag_acao_penal TEXT,
    flag_improbidade TEXT,
    flag_conflito_fundiario TEXT,
    flag_familia TEXT,
    flag_infancia TEXT,
    flag_infancia_civel TEXT,
    flag_infancia_infracional TEXT,
    flag_infancia_ato_infracional TEXT,
    flag_racismo TEXT,
    flag_cacol TEXT,
    flag_previdenciario TEXT,
    flag_convecao_haia_1980 TEXT,
    -- Polos
    polo_ativo TEXT,
    cnpj_ativo TEXT,
    natureza_ativo TEXT,
    cnae_ativo TEXT,
    segmento_ativo TEXT,
    qtd_pf_at TEXT,
    qtd_pj_at TEXT,
    qtd_pf_pa TEXT,
    qtd_pj_pa TEXT,
    polo_passivo TEXT,
    cnpj_passivo TEXT,
    natureza_passivo TEXT,
    cnae_passivo TEXT,
    segmento_passivo TEXT,
    -- Administrativo
    poder_publico TEXT,
    ano_eleicao TEXT,
    id_orgao_julgador_colegiado TEXT,
    assistencia_judiciaria TEXT,
    flg_pedido_prioridade TEXT,
    flg_nucleo_4 TEXT,
    flg_juizo_100_digital TEXT,
    custas_iniciais TEXT,
    custas_recursais TEXT,
    custas_finais TEXT,
    -- Auditoria
    millisinsercao TEXT,
    created_at TEXT,
    updated_at TEXT
);
